package com.ktxdevelopment.mobiware.util

object Constants {

     const val NOTHING = "nothing"
     const val TECNO: String = "tecno"
     const val ENERGIZER = "energizer"
     const val TCL = "tcl"
     const val ULEFONE: String = "ulefone"
     const val MEIZU = "meizu"
     const val MOTOROLA = "motorola"
     const val HTC = "htc"
     const val CAT: String = "cat"
     const val BLACKVIEW: String = "blackview"
     const val ASUS = "asus"
     const val ALCATEL: String = "alcatel"
     const val BLU ="blu"
     const val REF_EXTRA: String = "image_ref"
     const val BRAND_EXTRA: String = "brand_extra"
     const val ID_EXTRA: String = "uid_worker"
     const val SLUG_EXTRA: String = "slug"
     const val MOBILE_ID = "mobileId"
     const val FR_PROFILE: String = "profile_fr"
     const val FR_FEEDBACK: String = "feedback_fr"
     const val PHOTOS: String = ""
     const val IMAGE_EXTRA: String = "image_extra"
     const val FEEDBACK_EXTRA: String = "feedback_extra"
     const val USER_PASSWORDS: String = "userPasswords"
     const val DISPLAY = "display"
     const val CHIPSET = "chipset"
     const val PASSWORDS: String = "passwords"

     const val USER_EXTRA: String = "user_extra"
     const val LOCAL_USER: String = "local_user"
     const val PHONE_LIST: String = "phone_list"
     const val MOBILE_NUMBER_BASE: String = "mobileNumberBase"
     const val MOBILE_NUMBER_CODE: String = "mobileNumberCode"
     const val USERNAME: String = "username"
     const val IMAGE_ONLINE: String = "imageOnline"
     const val READ_STORAGE_CODE: Int = 1
     const val PHONE_EXTRA = "main_phone_extra"
     const val PREFERENCE_LOCK_KEY: String = "com.ktxdevelopment.mobiware.MY_PREFERENCE_FILE"
     const val USERS: String = "users"
     const val MOBILES = "mobiles"
     const val FEEDBACKS = "feedbacks"
     const val ANY_UPDATE: String = "any_update"
     const val UPDATE_SIGN: String = "update_sign"
     const val VERSION: String = "version"
     const val DB_NAME = "mobile_db"

     const val MAY = "may"
     const val MUST = "must"

     const val PR_userId = "user_userId"
     const val PR_username = "user_username"
     const val PR_mobileNumberBase = "user_mobileNumberBase"
     const val PR_mobileNumberCountryCode = "user_mobileNumberCode"
     const val PR_mobileId = "user_mobileId"
     const val PR_email = "user_email"
     const val PR_imageBase64: String = "user_image"
     const val PR_imageOnline: String = "user_image_url"
     const val PR_currentSlug:String = "user_phone_slug"

     const val XIAOMI = "xiaomi"
     const val SAMSUNG = "samsung"
     const val LG = "lg"
     const val REALME = "realme"
     const val HONOR = "honor"
     const val HUAWEI = "huawei"
     const val VERTU = "vertu"
     const val APPLE = "apple"
     const val LENOVO = "lenovo"
     const val OPPO = "oppo"
     const val VIVO = "vivo"
     const val NOKIA = "nokia"
     const val ONEPLUS = "oneplus"
     const val PHILIPS = "philips"
     const val SONY = "sony"
     const val VODAFONE: String = "vodafone"
     const val GOOGLE = "google"
     const val ZTE = "zte"

//     const val BASE_URL_4 = "https://api-mobilespecs.azharimm.site/v2/"
//     const val BASE_URL_3 = "https://phone-specs-api-azharimm.vercel.app/v2/"
//     const val BASE_URL_2 = "https://phone-specs-api.vercel.app/v2/"
     const val BASE_URL_1 = "https://phone-specs-api-git-master-azharimm.vercel.app/v2/"

     const val SEARCH_URL = "search"         // push ?query
     const val LATEST_URL = "latest"
     const val BRANDS_URL = "brands"

//    SEARCH_URL - "https://api-mobilespecs.azharimm.site/v2/search?query="
//    LATEST_URL - "https://api-mobilespecs.azharimm.site/v2/latest"
//    TOP_FANS_URL - "https://api-mobilespecs.azharimm.site/v2/top-by-fans"
}